### ISSUE TITLE
Help me broo.....KeyError: 'access_token'

### ISSUE THREAD

**Issue by razak95** [AlexKrutoy/TapSwapBot#11]
DevTools listening on ws://127.0.0.1:19895/devtools/browser/64872c34-5c3b-4f97-98f5-3194bee8417e
Traceback (most recent call last):
  File "C:\Users\akbar\TapSwapBot\bot\core\tapper.py", line 120, in login
    access_token = response_json['access_token']
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'
2024-06-20 17:33:47 | ERROR    | 126 - inna_tapswap | Unknown error while getting Access Token: 'access_token' | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
2024-06-20 17:33:47 | INFO     | 164 - All sessions are closed. Quitting driver...
2024-06-20 17:33:54 | ERROR    | 393 - inna_tapswap | Unknown error: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "C:\Users\akbar\TapSwapBot\bot\core\tapper.py", line 120, in login
    access_token = response_json['access_token']
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'
2024-06-20 17:33:54 | ERROR    | 126 - akbar_tapswap | Unknown error while getting Access Token: 'access_token' | Response text: {"statusCode":400,"message":"invalid_chr[2]"}...
2024-06-20 17:33:57 | ERROR    | 393 - akbar_tapswap | Unknown error: cannot unpack non-iterable NoneType object

**Comment by mironov1338** [comment]
Помогите такая же проблема
![image](https://github.com/AlexKrutoy/TapSwapBot/assets/157545258/2130413c-fb49-474e-82f1-3992052078b8)

**Comment by ButCheR-PRO** [comment]
Ждём фикса бота

**Comment by ButCheR-PRO** [comment]
Кстати тема дубликат 
1. https://github.com/AlexKrutoy/TapSwapBot/issues/10
