### ISSUE TITLE
 error while getting Access Token

### ISSUE THREAD

**Issue by mrdarkerr** [AlexKrutoy/TapSwapBot#4]
> 1
Traceback (most recent call last):
  File "/root/TapSwapBot/bot/core/tapper.py", line 112, in login
    chq_result = extract_chq(chq=chq)
  File "/root/TapSwapBot/bot/utils/scripts.py", line 132, in extract_chq
    driver = web_driver(service=web_service(webdriver_path), options=options)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/root/TapSwapBot/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

2024-06-14 03:15:48 | ERROR    | 126 - +9 | Unknown error while getting Access Token: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
 | Response text: {"chq":"fbe8f3fee9f4f2f3bdfcb5b4e6ebfcefbdefa0c6baacabadaaaba5a5ccded8ccf8dcbab1baaca9f2dbecd5f5d9bab1baa4afafaaaaabf3d6e5dbefebbab1baacaaa5a9a8adafc8d3c9f2f1ecbab1baacacadf8d7f1dad3fabab1baacadaba4ada4acf2c5d0eff1cebab1baaca8aaa9aeababcddcf8dfc5dbbab1baa...

**Comment by AnhAnhii** [comment]
Same error

**Comment by zexry619** [comment]
same

**Comment by AlexKrutoy** [comment]
Установи браузер хром / download chrome browser

**Comment by headNbyte** [comment]
@mrdarkerr you should run the `sh install.sh` since you don't have firefox installed
