### ISSUE TITLE
Downloading webdriver

### ISSUE THREAD

**Issue by thanhturau** [AlexKrutoy/TapSwapBot#5]
2024-06-14 10:16:38 | INFO     | 51 - Downloading webdriver. It may take some time...

**Comment by shelllshock** [comment]
Не стартует вебдрайвер. Подскажите, куда копать?
2024-06-14 07:25:33 | INFO     | 51 - Downloading webdriver. It may take some time...
Traceback (most recent call last):
  File "C:\TapSwapBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\TapSwapBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\TapSwapBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\TapSwapBot\bot\core\tapper.py", line 17, in <module>
    from bot.utils.scripts import extract_chq, escape_html
  File "C:\TapSwapBot\bot\utils\scripts.py", line 53, in <module>
    webdriver_path = pathlib.Path(web_manager().install())
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TapSwapBot\venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
